name: "bench"
on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 'build with docker'
      run: |
        docker build -t fluent-plugin-s3-arrow .
    - name: 'bench'
      id: 'bench'
      run: |
        docker run fluent-plugin-s3-arrow /bin/bash -c "benchmark-driver benchmark/compress.yml"
    - name: 'bench memory'
      id: 'bench_mem'
      run: |
        docker run fluent-plugin-s3-arrow /bin/bash -c "benchmark-driver benchmark/compress.yml --runner memory"
